create table categorias_base (
    id integer generated by default as identity primary key,
    nome varchar(100) not null,
    slug varchar(120) not null unique,
    descricao varchar(255),
    ativo boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table clientes (
    id integer generated by default as identity primary key,
    nome varchar(150) not null,
    whatsapp varchar(20) not null,
    email varchar(120),
    cpf varchar(14),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table enderecos_entrega (
    id integer generated by default as identity primary key,
    cliente_id integer,
    zip_code varchar(9) not null,
    state varchar(2) not null,
    city varchar(100) not null,
    district varchar(100) not null,
    street varchar(150) not null,
    number varchar(20) not null,
    complement varchar(100),
    reference varchar(150),
    full_address varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_enderecos_entrega_cliente
        foreign key (cliente_id) references clientes (id) on delete set null
);

create table pedidos (
    id integer generated by default as identity primary key,
    code varchar(40) not null unique,
    loja_id integer not null,
    cliente_id integer not null,
    address_id integer,
    subtotal numeric(12, 2) not null,
    shipping_cost numeric(12, 2) not null default 0,
    total numeric(12, 2) not null,
    payment_method varchar(30) not null,
    payment_status varchar(30) not null,
    order_status varchar(30) not null,
    delivery_type varchar(20) not null,
    notes varchar(500),
    items_count integer not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_pedidos_loja
        foreign key (loja_id) references lojas (id),
    constraint fk_pedidos_cliente
        foreign key (cliente_id) references clientes (id),
    constraint fk_pedidos_endereco
        foreign key (address_id) references enderecos_entrega (id) on delete set null
);

create table pedido_itens (
    id integer generated by default as identity primary key,
    pedido_id integer not null,
    produto_id integer,
    category_id integer,
    product_name_snapshot varchar(160) not null,
    quantity integer not null,
    unit_price numeric(12, 2) not null,
    line_total numeric(12, 2) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_pedido_itens_pedido
        foreign key (pedido_id) references pedidos (id) on delete cascade,
    constraint fk_pedido_itens_produto
        foreign key (produto_id) references produtos (id) on delete set null,
    constraint fk_pedido_itens_categoria
        foreign key (category_id) references categorias (id) on delete set null
);

create table movimentacoes_estoque (
    id integer generated by default as identity primary key,
    loja_id integer not null,
    produto_id integer,
    pedido_id integer,
    movement_type varchar(20) not null,
    movement_source varchar(20) not null,
    quantity integer not null,
    previous_stock integer not null,
    current_stock integer not null,
    note varchar(255),
    created_at timestamp not null default current_timestamp,
    constraint fk_movimentacoes_estoque_loja
        foreign key (loja_id) references lojas (id),
    constraint fk_movimentacoes_estoque_produto
        foreign key (produto_id) references produtos (id) on delete set null,
    constraint fk_movimentacoes_estoque_pedido
        foreign key (pedido_id) references pedidos (id) on delete set null
);

create table pedido_status_historico (
    id integer generated by default as identity primary key,
    pedido_id integer not null,
    status varchar(30) not null,
    description varchar(255),
    created_at timestamp not null default current_timestamp,
    constraint fk_pedido_status_historico_pedido
        foreign key (pedido_id) references pedidos (id) on delete cascade
);

create table pagamentos (
    id integer generated by default as identity primary key,
    pedido_id integer not null,
    payment_method varchar(30) not null,
    status varchar(30) not null,
    amount numeric(12, 2) not null,
    transaction_code varchar(80),
    payload_json text,
    paid_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_pagamentos_pedido
        foreign key (pedido_id) references pedidos (id) on delete cascade
);

create index idx_enderecos_entrega_cliente on enderecos_entrega (cliente_id);
create index idx_pedidos_loja on pedidos (loja_id);
create index idx_pedidos_cliente on pedidos (cliente_id);
create index idx_pedido_itens_pedido on pedido_itens (pedido_id);
create index idx_pedido_itens_produto on pedido_itens (produto_id);
create index idx_movimentacoes_estoque_loja on movimentacoes_estoque (loja_id);
create index idx_movimentacoes_estoque_produto on movimentacoes_estoque (produto_id);
create index idx_movimentacoes_estoque_pedido on movimentacoes_estoque (pedido_id);
create index idx_pedido_status_historico_pedido on pedido_status_historico (pedido_id);
create index idx_pagamentos_pedido on pagamentos (pedido_id);
