create table usuarios (
    id integer generated by default as identity primary key,
    nome varchar(120) not null,
    email varchar(120) not null unique,
    telefone varchar(20) not null,
    cep varchar(9) not null,
    logradouro varchar(150) not null,
    numero varchar(20) not null,
    complemento varchar(100),
    bairro varchar(100) not null,
    cidade varchar(100) not null,
    estado varchar(2) not null
);

create table categorias (
    id integer generated by default as identity primary key,
    nome varchar(100) not null,
    descricao varchar(255) not null,
    usuario_id integer not null,
    constraint fk_categorias_usuario
        foreign key (usuario_id) references usuarios (id)
);
