create table lojas (
    id integer generated by default as identity primary key,
    name varchar(160) not null,
    slug varchar(160) not null unique,
    owner_name varchar(120) not null,
    owner_email varchar(120) not null unique,
    password_hash varchar(64) not null,
    whatsapp varchar(20) not null,
    cnpj varchar(14) not null unique,
    pix_key varchar(120) not null,
    zip_code varchar(9) not null,
    state varchar(2) not null,
    city varchar(100) not null,
    district varchar(100) not null,
    street varchar(150) not null,
    street_number varchar(20) not null,
    complement varchar(100),
    status varchar(20) not null default 'draft'
);
