create table produtos (
    id integer generated by default as identity primary key,
    loja_id integer not null,
    category_id integer not null,
    name varchar(160) not null,
    slug varchar(160) not null,
    description_short varchar(500),
    description_long text,
    sku varchar(80),
    price_retail numeric(12, 2) not null,
    price_wholesale numeric(12, 2),
    price_promotion numeric(12, 2),
    stock integer not null default 0,
    min_stock integer not null default 0,
    status varchar(40) not null default 'draft',
    is_featured boolean not null default false,
    notes varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_produtos_loja
        foreign key (loja_id) references lojas (id) on delete cascade,
    constraint fk_produtos_categoria
        foreign key (category_id) references categorias (id) on delete restrict,
    constraint uk_produtos_loja_slug unique (loja_id, slug)
);

create table produto_imagens (
    id integer generated by default as identity primary key,
    produto_id integer not null,
    filename varchar(255) not null,
    image_url varchar(255) not null,
    is_main boolean not null default false,
    position integer not null,
    constraint fk_produto_imagens_produto
        foreign key (produto_id) references produtos (id) on delete cascade
);
