create table produto_variantes (
    id integer generated by default as identity primary key,
    produto_id integer not null,
    size_label varchar(20) not null,
    price_retail numeric(12, 2),
    price_wholesale numeric(12, 2),
    price_promotion numeric(12, 2),
    stock integer not null default 0,
    min_stock integer not null default 0,
    position integer not null default 1,
    constraint fk_produto_variantes_produto
        foreign key (produto_id) references produtos (id) on delete cascade,
    constraint uk_produto_variantes_produto_tamanho unique (produto_id, size_label)
);
